### ISSUE TITLE
[Non Custodial Rate Limited PSM] Add forced deposit() on mint above specified threshold

### ISSUE THREAD

**Issue by ditchfieldcaleb** [fei-protocol/fei-protocol-core#571]
See comment here: https://github.com/fei-protocol/fei-protocol-core/pull/570#discussion_r819280152

We should add a threshold for a forced deposit() call when someone calls mint, which will prevent the DOS vector where someone cycles the PSM to pull all funds out of a pcv deposit.

**Comment by Joeysantoro** [comment]
Not totally convinced this is needed.

**Comment by ElliotFriedman** [comment]
This is majorly gas inefficient as it makes an external call to the PCV Deposit.

**Comment by ditchfieldcaleb** [comment]
@ElliotFriedman what about using Timed instead to ensure we call deposit every few days or so? That would prevent an external call.
