### ISSUE TITLE
[Non Custodial Rate Limited PSM] Check to make sure new pcv deposit underlying matches existing

### ISSUE THREAD

**Issue by ditchfieldcaleb** [fei-protocol/fei-protocol-core#572]
See this comment: https://github.com/fei-protocol/fei-protocol-core/pull/570#discussion_r819276367

We should check to make sure that any new/updated pcv deposit for a PSM uses the same token that this PSM expects; if a mistake is made here and the wrong one is used, we could burn a lot of cash.

**Comment by Joeysantoro** [comment]
agree

**Comment by ElliotFriedman** [comment]
done
