### ISSUE TITLE
[Non Custodial Rate Limited PSM] Allow minter address to be changed by governance

### ISSUE THREAD

**Issue by ditchfieldcaleb** [fei-protocol/fei-protocol-core#573]
See comment here:

https://github.com/fei-protocol/fei-protocol-core/pull/570#discussion_r819315922

Allowing the minter address to be changed by governance will let us do this instead of redeploying every contract that uses the minter when we update/redeploy the minter.

**Comment by Joeysantoro** [comment]
I agree, it should be changeable by governance

**Comment by ElliotFriedman** [comment]
This is a tradeoff space. Going with this design will be more gas inefficient as we will need to read from storage instead of using an immutable.

**Comment by ElliotFriedman** [comment]
I prefer keeping it immutable as the GlobalRateLimitedMinter will be very thoroughly reviewed and audited before going to production so it has a low likelihood of being swapped out.

**Comment by ditchfieldcaleb** [comment]
It's a single storage read, and I think the likelihood that we will *never* need to upgrade the minter is pretty low. Worth the gas cost imo.
