### ISSUE TITLE
Basic Protocol Monitoring

### ISSUE THREAD

**Issue by ditchfieldcaleb** [fei-protocol/fei-protocol-core#592]
In order to effectively use the PCV Sentinel to automate key tasks, we need to first have better visibility into the protocol as a whole. We have some basic monitoring up for PCV deposits and the PSM, as well as the collateralization ratio and PCV equity, but that's about it.

Monitoring can be broken down into three major constituent parts:

1) Continually identifying new / updated metrics to measure; new smart contracts that are deployed, shifting importance of metrics that cause new ones to need to be watched, and introduction of new systems that are critical to the protocol. This isn't trivial; this requires *all* engineers to be disciplined about sticking to process when making changes, and ensuring that their changes are monitored if needed. It's worth evaluating here whether we should have some kind of formal process for non-trivial protocol changes to ensure we have monitoring visibility.

2) A good way to filter noise and meaningless updates. This involves setting (and periodically re-evaluating) heuristics for various levels of alarms, as well as periodic summaries of trends of important metrics. This ties in pretty closely with 1), and mostly depends on what tools we use for alerting and how fine-grained they are. We do need to ensure that when selecting heuristics and their parameters that they are as resilient to normal-protocol-operation-change as possible, otherwise we create more work for the person maintaining the monitoring infrastructure.

3) A good way to visualize said data. Dashboards are cool, but not enough. This is arguably the hardest part. We want to be able to, at a glance, know what's going on with the system, but it shouldn't be too dense (because no one will look at it), but it should contain enough data to get a good feeling for how the protocol is doing as a whole. A great extra here would be some kind of network graph that highlights, with intensity corresponding to transaction size or something similar, usage of different parts of the system.

**Comment by ditchfieldcaleb** [comment]
Thoughts on 1) any formal process requires buy-in and commitment from the team. I highly suspect that without that, or even with half-hearted commitment, the job of "identity metrics that should be monitored with your change, and add them to the metric-monitoring system, and identify heuristics that should be tracked, and at what parameters they should alarm at" will be punted to the maintainer of the monitoring/alerting system (me).

@Joeysantoro thoughts on this? The above scenario seems honestly pretty likely without a decent culture shift, and might warrant someone working on this (and similar maintaince/updating tasks) full-time, which also isn't the worst-option.

**Comment by ditchfieldcaleb** [comment]
Thoughts on 2)

The period updating of heuristic parameters will similarly require buy-in and commitment from the team, or a dedicated person that is assigned to handle them.

**Comment by ditchfieldcaleb** [comment]
Thoughts on 3)

I'm going to do some research shortly on visualization tools like this. Datadog is a good resource and our current system is pretty workable in the meantime. If we go all-in on this we should consider adding more TVs to our office and some kind of small-form data-viz that works well on mobile, tablet, and small-screen formats.

**Comment by ditchfieldcaleb** [comment]
Thought: it would be SUPER helpful to have a visualization of where PCV is currently, where and when and how it flows through the system when it moves, and what operations triggered the movement.

**Comment by Joeysantoro** [comment]
> Thoughts on 1)
> 
> Any formal process requires buy-in and commitment from the team. I highly suspect that without that, or even with half-hearted commitment, the job of "identity metrics that should be monitored with your change, and add them to the metric-monitoring system, and identify heuristics that should be tracked, and at what parameters they should alarm at" will be punted to the maintainer of the monitoring/alerting system (me).
> 
> @Joeysantoro thoughts on this? The above scenario seems honestly pretty likely without a decent culture shift, and might warrant someone working on this (and similar maintaince/updating tasks) full-time, which also isn't the worst-option.

I think you're putting too much pressure on the team. Lets try to improve our monitoring setup and documentation from where it is and encourage everyone to pitch in, but I don't think this is blocked on consensus.

**Comment by Joeysantoro** [comment]
Theres basically two types of monitoring/alerting:
1. Stats and visualizations, which the current datadog and public analytics page seem good for
2. Alerting on known tx types, which defender and tenderly do pretty well

If its going to require some crazy overhaul, I'd want to be convinced of the benefit upfront given the resource constraints

**Comment by ditchfieldcaleb** [comment]
Okay tentative/draft plan:

To monitor existing stuff:
1) Use existing datadog & defender setup to monitor key metrics such as psm liquidity, co ratio, etc.
2) Create PCV flow diagram (static, just for reference at least initially)
3) Create general system diagram
4) Identify existing keepers and costs (including defender actions), and track this as a metric on datadog

To ensure we monitor when changes happen or for new stuff:
1) Add an integration test that will fail if there is a PCV deposit in mainnetAddresses that is not tracked in Defender (need to think about a good way to do this)

The one thing I can't come up with a quick solution for is parameter selection for our alerts - for example, each pcv deposit has a different level of tolerance we want for value before we alert on them, and this changes pretty often - how can we design this such that we don't have to keep reselecting parameters? Further categorization of pcv deposits might be helpful there. Will think about this over lunch.

**Comment by ditchfieldcaleb** [comment]
Refining this plan:

1) Documentation.
 - flow diagram for pcv, general system diagram
 - identify all keepers in the system

2) Identification of key metrics to monitor (and which ones we're already monitoring)

3) Identify shortcuts for easier monitoring params. Example: if we track the *total value* inflow and outflow from the system, we can alert on high levels of value inflow/outflow, instead of trying to track and be opinionated about every single pcv deposit.

4) Implement the above monitoring & configure alerts where feasible

5) Ensure that new contracts in the pcv (and others?) category are tracked by the above monitoring system with an integration test that fails fi it is not.

**Comment by Joeysantoro** [comment]
> 1. Documentation.
> 
> * flow diagram for pcv, general system diagram
> * identify all keepers in the system

Mainnetaddresse.json will be a good reference here. Also every contract with the Minter role and OZ defender scripts.

2. PSMs, size of the largest FEI and TRIBE deposit locations
3-4. Great

**Comment by ditchfieldcaleb** [comment]
`ctc fei pcv assets` ---> pipe amounts of each major asset Into datadog and monitor for significant changes

**Comment by ditchfieldcaleb** [comment]
Some thoughts:

- Raw numbers don't mean much. What we want to see is trends. If the derivative of some value graphed & smoothed over a time period is consistently negative, it could be a bad thing. Should we show multiple time periods here or choose just one?
- Big jumps in values should be alerted. This will happen occasionally as contracts are switched out.

**Comment by ditchfieldcaleb** [comment]
Closing this discussion thread and creating individually-actionable tickets.
