### ISSUE TITLE
Basic Protocol Automation

### ISSUE THREAD

**Issue by ditchfieldcaleb** [fei-protocol/fei-protocol-core#593]
Once we have good monitoring in place, we can automate key parts of the system.

This automation can likely be done almost entirely via the PCV sentinel; bespoke contracts may have to be written to handle some actions that the PCV sentinel can't.

We separate the automation into categories as such:

1) Security & Crisis Response. This includes things like "withdraw and cash out from a pcv deposit with a compromised underlying", "pause a fuse pool if its oracle has liquidity issues", or "initiate L1 withdrawal procedures for an L2 chain that has gone down", or "pause literally every PCV deposit".

2) Economic Optimization. This includes things like turning on and off each psm when parameters are met, such as "turn the eth psm on if the dai and lusd pcv deposits are low enough", or "turn the eth psm off when the collateralization ratio is low enough"

3) Utility & Efficiency Spells. I use the term "spell" here because some of these actions will essentially be that: incantations combining multiple single transactions into complete actions to accomplish some goal. One example would be "push liquidity to L2s that need it", one would be "gather yield from pcv deposits where needed", another might be "rebalance pcv among like-type deposits when too imbalanced".

We should ensure that each action taken by the Sentinel is logged somewhere central, and that we have good visibility into what it is doing.

**Comment by Joeysantoro** [comment]
These are sick and don't really require monitoring as a blocker. Its super simple to spin up a defender alert feed on sentinel actions

**Comment by ditchfieldcaleb** [comment]
Draft plan here is to create a list of many possible guards in each of the above three categories, prioritize them via generality and utility, and implement in a 1-3-2 order. Economic optimizations will be the most tailored of the guards and thus will come last; security and crisis response guards are clearly the most needed. Utility will make our dev cycles faster and _more pareto_.

**Comment by Joeysantoro** [comment]
Seems fine, I will say some of the "economic optimization" ones are much closer to security where PSMs are concerned for example

**Comment by ditchfieldcaleb** [comment]
Closing this discussion thread and creating individually-actionable tickets.
